{% set name = "pygelf" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3e5bc59e3b5a754556a76ff2c69fcf2003218ad7b5ff8417482fa1f6a7eba5f9

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - pygelf

about:
  home: https://github.com/keeprocking/pygelf
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python logging handlers with GELF (Graylog Extended Log Format) support.'
  description: |
    Python logging handlers with GELF (Graylog Extended Log Format) support.
    Currently TCP, UDP, TLS (encrypted TCP) and HTTP logging handlers are supported. 
  doc_url: https://github.com/keeprocking/pygelf
  dev_url: https://github.com/keeprocking/pygelf

extra:
  recipe-maintainers:
    - tberkey-ilw
    - tberkey
