{% set name = "pygelf" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8ed972563be3c8f168483f01dbf522b6bc697959c97a3f4881324b3f79638911

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pygelf

about:
  home: https://github.com/keeprocking/pygelf
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python logging handlers with GELF (Graylog Extended Log Format) support.'
  description: |
    Python logging handlers with GELF (Graylog Extended Log Format) support.
    Currently TCP, UDP, TLS (encrypted TCP) and HTTP logging handlers are supported. 
  doc_url: https://github.com/keeprocking/pygelf
  dev_url: https://github.com/keeprocking/pygelf

extra:
  recipe-maintainers:
    - tberkey-ilw
    - tberkey
