travis:
  secure:
    BINSTAR_TOKEN: Q1lWxxTW29jOzFDWTnM66j27LSDBU+O7fHTI10ACiy95rlzSNl6jqwdCaQLl7Dvni29KdyZcDjHxq1hGgvLfqfOFZI07L46bBawAqCb87Ts8XlgPrA4pCYybSZE8VTrl5zb/hZVHceL1/gjPhaUEDckSO1WRBZGcLY7jyEkLHq3yzgnQFRYBGsBAOSYyJRnSq0BtwfYU4bR6Yzk6iKaZoTkNfkhgywUfAE5fQqVbgfF9eTDx/+YDZPE9IEctyeRZoz7CTCq1ets9WFhWwzVjgGkouKGzDOJ4RiWX4Ppc3mBOtNffaWTd0xxvEB6jvvAT70Ni9NEgy8/o1p6Dyr6WMTHpCJVFLd9ZzTfCMrSR2trVYtg7bxiWNOOOrMB3gDtYBvnC67BH58/Cnw5NMOwFWrsZafy6p7LMDleHz2MPtgyrexLqjhAwK262mm7WVYm2Bj+D9Ffkbc8992TLhD3Y+5VQcj5qZIuFsTnclC5rX5pCMCSd/nmrEZPl/M/DrUGOyF1laugfDax247TeXwiv8ACAu0AKEUI1f1DBaBQ7P99VoqYLqBK5g7ajoY69f9CwijvoWQdFCZJBTm01+g7mM3OCWNm5x4hbIxLFs/52WFxOVAXajZigAE8R2lmmUK7CVIBb+wEV123Sqmt1O0Q4fS7KyLbPBl5okWAFyHQDmi4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
